### ISSUE TITLE
slow memory leak

### ISSUE THREAD

**Issue by senecaso** [nielsen-oss/fasttext-serving#1]
There is a slow memory leak somewhere in the code base.  The python process starts off small (~1GB), and over the course of several hours of processing many batch prediction requests, the resident memory of the process creeps up to 4GB, 5GB, etc, until finally the process is killed by the OOM killer.  I am using code from git commit `8aae32727a19`, which is fairly recent.  If there is more information I can provide, let me know.  I know very little about python, but I can gather information if required.

**Comment by senecaso** [comment]
fix: https://github.com/nielsen-oss/fasttext-serving/pull/5

**Comment by defr8001** [comment]
It is supposed to be fixed in PR #5 

Thanks for your contribution to this repo. If the memory leak is not solved, feel free to reopen this issue
