### ISSUE TITLE
Serve word vector model

### ISSUE THREAD

**Issue by bahar3474** [nielsen-oss/fasttext-serving#3]
Hi.
Can your method only be used if the supervised model is attached to it? I don't have a classification model. All I have is word vectors (.bin and .txt). How can I serve it?

**Comment by defr8001** [comment]
If you have trained your word vectors, you should have two files: a .bin and a .vec (ASCII). You should be able to load the .bin model as usual and retrieve the word vector using the RPC endpoint:

```
 rpc GetWordsVectors (VectorsRequest) returns (VectorsResponse); 
```

The fastText API allows to load both supervised and unsupervised models so it should work, but do not hesitate to contact us or make a PR if you find any problem.

https://github.com/facebookresearch/fastText/blob/master/docs/unsupervised-tutorials.md

BTW, the `predict` endpoint won't work in this case: https://github.com/facebookresearch/fastText/blob/a20c0d27cd0ee88a25ea0433b7f03038cd728459/python/fasttext_module/fasttext/FastText.py#L200
