### ISSUE TITLE
Trouble configuring client

### ISSUE THREAD

**Issue by supertulli** [nielsen-oss/fasttext-serving#7]
Hello.

First off, thanks for your work!

Been trying to use this to vectorize text to serve an ML clustering algorithm. I have set the setup.py on the client side, by running "python setup.py install" on the src folder of the ML app project while having the fts/protos folder inside de project folder, and it in fact builds the proto protocol folder into it. Still I'm having trouble as running the app issues the following error:

TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "service.proto":
  service.proto: A file with this name is already in the pool.

Any idea what I'm doing wrong? Clearly I don't understand enough of gPRC, for starters... ;)

Thanks again

Pedro

**Comment by defr8001** [comment]
Hi Pedro,

I'm not sure I'm getting your directory layout from the description you provided. Can you share your output from `tree <root-of-your-repo>`?

In addition, it seems like you have duplicated .proto files in the path of the -I flag of the protoc command. Can you start from scratch following the instructions specified in the README file from the root folder of the project?

https://github.com/nielsen-oss/fasttext-serving#quick-start

Thanks
