### ISSUE TITLE
No module named fts while executing sample/client.py

### ISSUE THREAD

**Issue by sandepp123** [nielsen-oss/fasttext-serving#9]
While running the final step i.e. `python sample/client`  in Quickstart, I am getting following error.
`Traceback (most recent call last):
  File "sample/client.py", line 19, in <module>
    import fts.protos.service_pb2_grpc
ModuleNotFoundError: No module named 'fts'
`
Tried to find solution from [protobuf/issues/1491](https://github.com/protocolbuffers/protobuf/issues/1491), but failed finding  a solution.

**Comment by defr8001** [comment]
make sure that the fts package has been installed in the previous instruction:

```
python3 setup.py install
```

you can use `pip list | grep fts`

**Comment by sandepp123** [comment]
Yes, the problem is due to fts not getting installed.
It gave warning of setup.py install is deprecated, so I installed setuptools==58.2.0 as it was a quickfix. Then executing 
`python3 setup.py install`
creates fts/protos 

> ├── fts
>  ├── __init__.py
>  ├── __main__.py
> │   ├── protos
> │   │   ├── __init__.py
> │   │   ├── model_pb2_grpc.py
> │   │   ├── model_pb2.py
> │   │   ├── service_pb2_grpc.py
> │   │   └── service_pb2.py
> │   ├── __pycache__
> │   │   └── __init__.cpython-36.pyc
> 
But there is no output while I execute. 

> pip list | grep fts

**Comment by defr8001** [comment]
Can you pull the latest changes in master and try again to install this package with `pip3 install .`?

**Comment by sandepp123** [comment]
That was quick, thank a lot.
